### ISSUE TITLE
Handle intermittent internet access

### ISSUE THREAD

**Issue by levackt** [AvinashSingh786/TruffleButter#19]
The refugee camps have wifi, though access is frequently interrupted.
We should allow the refugee to sign the transaction offline, and batch those for processing later.

See My Ether Wallet for handling offline transactions...

https://myetherwallet.github.io/knowledge-base/offline/making-offline-transaction-on-myetherwallet.html

**Comment by AvinashSingh786** [comment]
Crypto point of sale device will batch transactions and submit them when there is internet access available.
